### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by saifulbabo67646** [EnixCoda/SMS-Forward#1]
When i install my phone its show pop uo parsing error then i singed the app then also show same error. Please resolve its and also discuss how to built in number in source code for all time personal use.
Thanks for this great project.

**Comment by EnixCoda** [comment]
Hi @saifulbabo67646 

Would you provide more info on this? I'd like to know -

1. What device are you using?
2. Which Android version it is on?

---

If you want a built-in phone number, modifying code (rewrite `targetNumber` to your number) would be the simplest way to do that.

https://github.com/EnixCoda/SMS-Forward/blob/8d33e61c224f5191108a84ed7acde1fee4116d93/app/src/main/java/one/enix/smsforward/SMSReceiver.java#L23

**Comment by saifulbabo67646** [comment]
Sir its showing this error .. And my phone version is 6.0. Thanks for your
reply

**Comment by EnixCoda** [comment]
Sorry, did you forgot to attach your screenshot?

**Comment by saifulbabo67646** [comment]
Sorry si,,  this is the photo of the error

**Comment by saifulbabo67646** [comment]
Please sir give me your email address... I want talk to you
