### ISSUE TITLE
Can we Forward the SMS to a URL

### ISSUE THREAD

**Issue by aniakg** [EnixCoda/SMS-Forward#4]
Hi,

This is a good app, just wanted to check, instead of forwarding the SMS to a number, can we forward it to the URL.
If it is possible then I request you to please provide the code for that. 

Thanks & Regards,
Anil Kumar

**Comment by EnixCoda** [comment]
@aniakg That is absolutely possible. I do not know Java and Android development much and cannot implement that easily. I'd suggest you ask for help from a professional. :)

**Comment by AchoArnold** [comment]
Hello @aniakg,

As an alternative, you can checkout this project https://github.com/NdoleStudio/httpsms which supports forwarding received SMS messages to a webhook.

Thanks.

**Comment by EnixCoda** [comment]
Now supported
