### ISSUE TITLE
Sms is not sending 

### ISSUE THREAD

**Issue by Ravanka** [EnixCoda/SMS-Forward#5]
![Screenshot_20220221-193945_Messages.jpg](https://user-images.githubusercontent.com/100142165/154971112-239ecf86-cd1a-47cb-a660-aa643765510a.jpg)

**Comment by EnixCoda** [comment]
This app only supports forwarding to phone numbers, not names like `TM-MSHOTP`

**Comment by Ravanka** [comment]
How to forward itps and all
