### ISSUE TITLE
Curious About Software Licensing Status

### ISSUE THREAD

**Issue by scriptgenerator64** [EnixCoda/SMS-Forward#6]
Hi,
I noticed that there is no LICENSE file in this repo. Are we allowed to copy your code for commercial purposes or only for personal projects? And in either case, do we need to maintain the open-source status of the project or can we make it closed source (not that I plan on doing that)?

Thanks

**Comment by EnixCoda** [comment]
Hi @scriptgenerator64 

I added license field to readme.

This project is under MIT license. 😎

**Comment by scriptgenerator64** [comment]
Amazing!
